### ISSUE TITLE
Styling form-field__help / .validation-error

### ISSUE THREAD

**Issue by sebastianroming** [PredixDev/px-datetime-field#5]
Hello,

currently it isn't possible to style any validation error message except the text color, as `/deep/` and `::shadow` is deprecated. 
As it doesn't fit in our design principles, we should give the wrapping div a padding and a background-color.
Could you please introduce a possibility to do this, or, if there is any, give me a solution? 

![px-datetime-field-error](https://user-images.githubusercontent.com/200112/29454399-4f645324-840d-11e7-83de-2aa32bc013e5.PNG)

Thank you.

**Comment by katemenkhaus** [comment]
Hi sebastianroming, 

The redesigned `px-datetime-field` has a height of about 50px. The component needs to fit inside of a container with at least that much space so that it can be displayed correctly. 

We aren't going to introduce the ability to style the component only when the validation error is showing. Add that functionality would go against the design of the component. 

Thanks, 
Kate

**Comment by sebastianroming** [comment]
Thanks @Menkhaus-ge for that information. 
That doesn't really fit in our design principles, but we'll give it a try.
